### ISSUE TITLE
No documentation showing how to use skywalker at all

### ISSUE THREAD

**Issue by tstibbs** [jprante/elasticsearch-skywalker#9]
I know the readme says "documentation not ready yet", but it gives some sample output. Nowhere does it say how to get any output. Should I be running something on the command line, or making some http request, or what?

(if I've missed a bit of the doc that contains this instruction then feel free to point it out and close this issue).

Thanks.

**Comment by joanteixi** [comment]
HI, 

we think that the way is: localhost:PORT/YOUR_INDEX/_skywalker

**Comment by jprante** [comment]
README was updated, closed.
